-- MySQL Script generated by MySQL Workbench
-- Sun Feb 24 20:30:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jeep
-- -----------------------------------------------------
-- jeep数据库
DROP SCHEMA IF EXISTS `jeep` ;

-- -----------------------------------------------------
-- Schema jeep
--
-- jeep数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jeep` DEFAULT CHARACTER SET utf8 ;
USE `jeep` ;

-- -----------------------------------------------------
-- Table `jeep`.`j_nav_img`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jeep`.`j_nav_img` ;

CREATE TABLE IF NOT EXISTS `jeep`.`j_nav_img` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '导航标对应的图片';


-- -----------------------------------------------------
-- Table `jeep`.`j_nav`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jeep`.`j_nav` ;

CREATE TABLE IF NOT EXISTS `jeep`.`j_nav` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nav` VARCHAR(45) NOT NULL,
  `pid` INT NOT NULL COMMENT 'pid与当前表的id关联',
  `iid` INT NOT NULL COMMENT 'iid与j_nav_img表的id关联',
  PRIMARY KEY (`id`, `pid`, `iid`),
  INDEX `pid` (`pid` ASC) INVISIBLE,
  INDEX `iid` (`iid` ASC) INVISIBLE,
  CONSTRAINT `pid`
    FOREIGN KEY (`pid`)
    REFERENCES `jeep`.`j_nav` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `iid`
    FOREIGN KEY (`iid`)
    REFERENCES `jeep`.`j_nav_img` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '导航表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
